# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SNOWSQL_PWD: ${{secrets.SNOWFLAKE_PASS}}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  # deploy:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Install snowsql 
  #       run: |
  #             curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.32-linux_x86_64.bash
  #             SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.32-linux_x86_64.bash
  #             source ~/.profile
  #
  #     - name: Run SQL scripts
  #       run: |
  #             source ~/.profile         
  #             for file in "scripts/migrate"/*; do
  #               echo "Processing file: $file"
  #               snowsql -a AUFDSKR-SO14294 -u novachevski -f $file
  #             done
  inventory:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3 
     - name: update inventory 
       working-directory: snowflake-inventory/
       run: |
              sudo apt install openjdk-11-jdk
              sudo apt install graphviz
              java -jar schemaspy.jar -configFile config/snowflake.properties -debug -t snowflake -account AUFDSKR-SO14294 -role ACCOUNTADMIN -warehouse SF_TUTS_WH  -dp jdbc/snowflake-jdbc-3.0.14.jar -o output/

     - name: Deploy 
       uses: JamesIves/github-pages-deploy-action@v4
       with:
          folder: snowflake-inventory/output

  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3
  #
  #     # Runs a set of commands using the runners shell
  #     - name: Run SQL scripts
  #       run: |
  #             source ~/.profile         
  #             for file in "scripts"/*; do
  #               echo "Processing file: $file"
  #               snowsql -a AUFDSKR-SO14294 -u novachevski -f $file
  #             done
